version: '3'
services:
  db:
    image: postgres:13.2-alpine
    container_name: zorgrank_db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 35432:5432
